# Build stage builds the JAR
FROM gradle:jdk11-openj9 AS builder

# Create build directory
RUN mkdir /build

# Copy files into build container
COPY . /build

# Change to build directroy
WORKDIR /build

# Build the JAR
RUN gradle build

# Final Stage copies the JAR from previous builder and setups to run
FROM gcr.io/distroless/java:11

# Use non root user
USER nonroot:nonroot

# Copy JAR from builder changing ownership to the java user
COPY --from=builder --chown=nonroot:nonroot /build/build/libs/*.jar app.jar

# Set entry point to start app
ENTRYPOINT ["java","-jar","/app.jar"]
