# Build stage builds the JAR
FROM gradle:jdk8-openj9 AS builder

# Create build directory
RUN mkdir /build

# Copy files into build container
COPY . /build

# Change to build directroy
WORKDIR /build

# Build the JAR
RUN gradle build

# Final Stage copies the JAR from previous builder and setups to run
FROM openjdk:16-jdk-alpine

# Change user so that we are not using root
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# Copy JAR from builder
COPY --from=builder /build/build/libs/*.jar app.jar

# Set entry point 
ENTRYPOINT ["java","-jar","/app.jar"]
